name: test

on:
  push:
  pull_request:

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.98.1
      - run: cargo test --workspace
